apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: ENVIRONMENT
          value: "staging"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
